### PR TITLE
Custom font powered by kmeans clustering

### PR DESCRIPTION
**Pull request by cdluminate**
This is still a work-in-progress, don't merge.

The core part has been finished. The remaining work is parameter tuning.

Closes: https://github.com/hpjansson/chafa/issues/20

### CODE REVIEW

**Comment by cdluminate** [comment]
A side note about licensing: I'm not going to use a free (CC-* licensed or alike) image dataset. Thus the resulting font may have problem to be distrributed under the GPL license family. In this case I prefer to use MIT/Expat.

**Comment by hpjansson** [comment]
> @hpjansson How to add a new symbol type?
> 
> I tried to add
> 
> ```
> chafa/chafa-symbol-map.c
> + { "custom", CHAFA_SYMBOL_TAG_CUSTOM },
> 
> chafa/chafa-symbol-map.h
> + CHAFA_SYMBOL_TAG_CUSTOM       = (1 <<  15),
> ```
> 
> but the main program still doesn't recognize `--symbols custom`

That should work. Is it giving you an error message?

**Comment by cdluminate** [comment]
@hpjansson I figured out the cause of the problem I encountered yesterday. The newly compiled chafa used the shared object provided by libchafa0 instead of the newly compiled one.

Here is a preview:
2018-10-11-084835_1920x1080_scrot

I still need to tune the some parameters until I get a relatively good result.
This looks much better than BE256 and BE512, right?

**Comment by cdluminate** [comment]
Many screenshots for demonstration. The final result would be better than the follows

top: symbols=custom, bottom: symbols=block

2018-10-11-085937_1074x1517_scrot
2018-10-11-090312_1065x1560_scrot
2018-10-11-090457_1077x1435_scrot
2018-10-11-090529_1079x1558_scrot
2018-10-11-090709_1079x1555_scrot
2018-10-11-090841_1079x1226_scrot
2018-10-11-090917_629x1567_scrot
2018-10-11-091001_812x1565_scrot
2018-10-11-091125_1079x1308_scrot
2018-10-11-091222_1079x1434_scrot

**Comment by cdluminate** [comment]
I believe this will beat any existing unicode, or non-standard unicode. @kilobyte

**Comment by cdluminate** [comment]
More demo
2018-10-11-092414_1061x1554_scrot

**Comment by cdluminate** [comment]
Gnome wallpapers
Please ignore the missing font for `0x10cf00`.

2018-10-11-093757_1051x1200_scrot
2018-10-11-093809_1050x1202_scrot
2018-10-11-093852_1063x1203_scrot
2018-10-11-093906_1049x1319_scrot
2018-10-11-093916_1014x1325_scrot
2018-10-11-093956_1022x1408_scrot
2018-10-11-094004_1030x1416_scrot

**Comment by hpjansson** [comment]
Very nice. You can sort of tell that it generated edges at various angles. Two comments: There are horizontal stripe artifacts that I noticed with be256 too, maybe something's slightly off in the font generation step. Also there's a bit of noise -- is the training set noisy? Maybe it could be improved with high-contrast input in black & white, like line art or cartoons or something.

**Comment by cdluminate** [comment]
> Very nice. You can sort of tell that it generated edges at various angles. Two comments: There are horizontal stripe artifacts that I noticed with be256 too, maybe something's slightly off in the font generation step. Also there's a bit of noise -- is the training set noisy? Maybe it could be improved with high-contrast input in black & white, like line art or cartoons or something.

I doubt the those 1-pixel stripes are caused by some glitches in the font itself. I'll try to figure it out.

The generated glyphs are noisy because natural images are noisy. I can apply sort of post processing step to make these glyphs "smoother".

If you look into the code, you will find that each sample in the dataset is taken as follows:
```
image = readimage(path)
region = random_crop(image)
sample = region.resize(8, 8).convert(0-1-map)
```

**Comment by cdluminate** [comment]
I fixed the font by adding an offset to the blocks. It's a font rendering problem if there is still stripes. By adjusting the font size, sometimes those stripes will disappear.

**Comment by cdluminate** [comment]
With the latest default parameters, a dataset consisting of nearly 8 million samples. 12-threads kmeans algorithm requires 64GB of mem to avoid out-of-mem error. The clustering algorithm had been running for more than 7 hours...

**Comment by cdluminate** [comment]
Another good example
2018-10-13-074145_802x1178_scrot

**Comment by cdluminate** [comment]
I don't know if any user would like a font in this style (using "mean" convolution kernel during postprocessing).

**Comment by cdluminate** [comment]
I can start to prepare to finalize this work now (squash and rebase all the commits to make every commit clear). This font works well in `sakura` terminal. But it will become a disaster in QT based terminals (I think there are bugs in both my font and terminal emulator itself). Can we merge this work to master even it we know it currently won't work for QT-based terminals? @hpjansson

**Comment by cdluminate** [comment]
> Before this goes into an official release, I think it's important to freeze the font symbols so generated output becomes forward-compatible.

Theoretically I don't like keeping forward-compatibility for automatically and randomly generated stuff such as this set of glyphs/fonts. That said, freezing the glyph set is still possible, but I'll need some time to choose the best result.

> As for terminals, I'd like for it to work ok in at least xterm and libvte-based terminals (gnome-terminal, xfce terminal and so on).

This font should be fine with vte-based terminals (my terminal is sakura). But I believe I need some help from font expert on the font gap problem. The gaps between my font would even change after I changed my default font for sakura ...

> Wrt. licensing, would you consider using LGPLv3+ or GPLv3+ for the code, and any suitable free/oss license for the font(s)? It's simpler if all the code in the package is the same license. You could multilicense if you also want to release it under e.g. MIT.

LGPLv3+ for the code is fine to me, I'll relicense my code. Some investigation on the font license is required because the font is generated by using academic image dataset.

**Comment by cdluminate** [comment]
That said, the current status of this set of font is much better than the above showcases...

**Comment by hpjansson** [comment]
> Theoretically I don't like keeping forward-compatibility for automatically and randomly generated stuff such as this set of glyphs/fonts. That said, freezing the glyph set is still possible, but I'll need some time to choose the best result.

Yeah. I was thinking that if it generates a set of 256 (or 512, or...) glyphs that's fairly optimal for many different use cases, it could be shipped for people who don't want to generate their own, or who perhaps want to distribute pre-rendered ANSI images based on the glyph set, say, by using it in login banners, things like that. Users could just install a font to enable them to see this new super-duper class of character-based images.

> This font should be fine with vte-based terminals (my terminal is sakura). But I believe I need some help from font expert on the font gap problem. The gaps between my font would even change after I changed my default font for sakura ...

Ok if we hold off with the merge until we figure out what's causing it? libvte isn't entirely without bugs either -- what does it look like in xterm?

> LGPLv3+ for the code is fine to me, I'll relicense my code. Some investigation on the font license is required because the font is generated by using academic image dataset.

Great, thanks. As far as I'm concerned, the font can be any license as long as recipients are allowed to redistribute it freely. If not, it's better to find a different image set or simply not ship any font at all.

**Comment by cdluminate** [comment]
This PR is replaced by https://github.com/hpjansson/chafa/pull/24 because it takes very long time to load pictures. however I'll keep this branch for some time because this branch contains prebuilt font.

**Pull request closed without merging**
