### PR TITLE
[WIP/Don't merge] Higher Resolution character art with Custom font

### PR DESCRIPTION
**Pull request by cdluminate**
The finest resolution of block symbols in Unicode is 2x2.
I created a finer font with 3x3 resolution block symbols. The custom font use private area of Unicode, and starts from `0x10c0001`.

The resolution is 3x3, so the number of all possible blocks is the ninth power of 2, i.e. 512.

We can create 4x4 resolution font which fits better with 8x8 mask in chafa-symbols.c, but 4x4 resolution results in 2^16 = 65536 symbols. Maybe the performance will decrease drastically with such resolution. So I created 3x3 blocks instead.

The 3x3 resolution version is called BE512, i.e. "Block Extended 512".

Remaining works
===

- [ ] add definition in autoconf and C source to guard the usage of custom font
- [ ] sort of segfault when enabled all content from BE512.c
- [ ] add new tag: CHAFA_SYMBOL_TAG_BE512
- [ ] Are custom blocks in 3x3 resolution really improving the visual experience?

### CODE REVIEW

**Comment by cdluminate** [comment]
The following patch will add those finer blocks to chafa

```diff
diff --git a/chafa/chafa-symbols.c b/chafa/chafa-symbols.c
index 68ba94b..67f7497 100644
--- a/chafa/chafa-symbols.c
+++ b/chafa/chafa-symbols.c
@@ -1858,6 +1858,7 @@ static const ChafaSymbolDef symbol_defs [] =
         " XXX XXX"
         "XX XXX X"
     },
+#include "BE512.c"
     {
         0, 0, ""
     }
```

```
~/p/c/chafa.orig ❯❯❯ ./chafa/chafa --symbols block /usr/share/backgrounds/gnome/ColdWarm.jpg --symbols block
fish: “./chafa/chafa --symbols block /…” terminated by signal SIGSEGV (Address boundary error)
```

However, chafa would segfault even if it was successfully compiled. I tried to comment out code in BE512.c in a binary selection manner, and discovered that at least the first 1000 lines are working. Maybe the segfault is due to conflicting bit map?

**Comment by cdluminate** [comment]
Before v.s. After. It appears that the blocks in 3x3 resolution indeed made some significant difference.

**Comment by cdluminate** [comment]
@hpjansson How do you like this?

**Comment by hpjansson** [comment]
This is interesting work -- I'll review it more thoroughly later. For now, maybe you can avoid the crash if you increase the `CHAFA_N_SYMBOLS_MAX` constant here: https://github.com/hpjansson/chafa/blob/def00a04c0264c3ac7354b339c5b29935dd6aacf/chafa/chafa-private.h#L54

Since you're adding 512 symbols, I think it should be enough to double it to 2048. Eventually I want to make it fully dynamic and get rid of the constant.

**Comment by hpjansson** [comment]
Also, the braille range may be a close analog to what you're doing. Its symbols are generated dynamically since they're regular and there's 256 of them (2x4 bits): https://github.com/hpjansson/chafa/blob/def00a04c0264c3ac7354b339c5b29935dd6aacf/chafa/chafa-symbols.c#L2016

**Comment by cdluminate** [comment]
Still segfault even if I bumped the max to 4096

```diff
diff --git a/chafa/chafa-private.h b/chafa/chafa-private.h
index 5db8100..f5b2dfc 100644
--- a/chafa/chafa-private.h
+++ b/chafa/chafa-private.h
@@ -51,7 +51,7 @@ ChafaPaletteColor;
 
 /* Character symbols and symbol classes */
 
-#define CHAFA_N_SYMBOLS_MAX 1024  /* For static temp arrays */
+#define CHAFA_N_SYMBOLS_MAX 4096  /* For static temp arrays */
 #define CHAFA_SYMBOL_N_PIXELS (CHAFA_SYMBOL_WIDTH_PIXELS * CHAFA_SYMBOL_HEIGHT_PIXELS)
 
 typedef struct
diff --git a/chafa/chafa-symbols.c b/chafa/chafa-symbols.c
index 68ba94b..a21e4d2 100644
--- a/chafa/chafa-symbols.c
+++ b/chafa/chafa-symbols.c
@@ -1858,6 +1858,7 @@ static const ChafaSymbolDef symbol_defs [] =
         " XXX XXX"
         "XX XXX X"
     },
+#include "../font/BE512.c"
     {
         0, 0, ""
     }
```

**Comment by cdluminate** [comment]
Each .svg file is in a resolution of 1000px * 1000px (required by fontforge, see fontforge's "importing from inkscape" doc). The actual character takes the [0:500, 0:1000] (left half) area, and the rest part is for double width characters.

So I think it makes sense to create another set of block symbols named BE256 (resolution 2x4). In this case the smallest block in svg file would be 250px*250px square. This is similar to braille but I expect a better look than braille.

**Comment by kilobyte** [comment]
Unlike official Unicode characters, the vast majority of users won't have your custom font installed.  Thus, usefulness of this feature is pretty limited.  Well, there _is_ an insane person working on arbitrarily large fonts for Linux console but that's pretty much the only use — on a local X terminal you can as well display the image graphically, and unlike regular **chafa** output, you can't send it to someone else.

**Comment by kilobyte** [comment]
2x4 matrix sounds a lot better than 4x4 or 3x3 — the aspect ratio of most fonts is very close to 1:2.  It used to vary widely in the past: from 1:2.5 on PC-like text mode to 1:1 on 8-bit machines, but new fonts seem to quickly converge on exactly 1:2.

My theory is that's because of CJK people: Chinese typography rules demand square glyphs while Western people don't care much, thus font makers do what will make a mixed text look good.  Just a guess...

**Comment by hpjansson** [comment]
The way I see this working is as an optional symbol class that would be disabled by default and not included in the "all" superclass -- though maybe it could belong to an "extra" superclass or something like that. The user would have to ask for it specifically with --symbols be256, and it'd be like a poor man's sixels.

Another font dependency it'd be cool to support is this one: http://style64.org/c64-truetype -- specifically in the U+E0xx range -- it has a couple PETSCII symbols that are not in official Unicode. Just for fun :slightly_smiling_face:

**Comment by kilobyte** [comment]
There's also an official proposal here: https://www.unicode.org/L2/L2017/17435r-terminals-prop.pdf — not yet voted upon.

**Comment by hpjansson** [comment]
Nice. Wrt. PETSCII it's probably better to wait for that, then.

**Comment by hpjansson** [comment]
@cdluminate 84a38d599d57fe9b16011d04b5397e5b660a8e70 fixes the crash you ran into.

**Comment by cdluminate** [comment]
@hpjansson Do you want the BE256 or BE512 font? I think https://github.com/hpjansson/chafa/issues/19 is what the custom font should focus on.

If you like the BE256 or BE512 font, I can finish this PR. Or I will close this PR and change these scripts to generate font for https://github.com/hpjansson/chafa/issues/19 .

**Comment by cdluminate** [comment]
Closed. This branch could be used as a reference for creating custom font for #19

**Pull request closed without merging**
