### PR TITLE
tools/fontgen: doc and python script updates.

### PR DESCRIPTION
**Pull request by cdluminate**
(1) documentation update for README.md. The optional command line arguments are explained. The steps and the results are elaborated. The python dependencies are mentioned.
(2) svg2ttf.py is upgraded from Python2 to Python3 (Python2 is EOL).

### CODE REVIEW

**Comment by cdluminate** [comment]
@hpjansson I've done my updates. Please review and merge :-)

**Comment by hpjansson** [comment]
Great stuff! I've tested it and it works -- but I think it might need one small correction to make the font understandable to the `chafa` glyph importer. I'll merge this and then we can update it incrementally.

**Comment by cdluminate** [comment]
> Great stuff! I've tested it and it works -- but I think it might need one small correction to make the font understandable to the `chafa` glyph importer. I'll merge this and then we can update it incrementally.

Sure, could you please open a new issue regarding this?

**Comment by hpjansson** [comment]
Ah, I just added a comment about it in #29. Turning that into a catch-all for fontgen polishing.

**Pull request merged**
