### PR TITLE
Use sixel mode by default in Contour terminal

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by hpjansson** [comment]
Hi, thanks for the PR! I think it needs a small correction -- could you use something like:

```
if (!g_ascii_strcasecmp (term_program, "contour"))
{
  ...
}
```

Note the `!` (inverted logic).

**Comment by data-man** [comment]
Hi!

> `if (!g_ascii_strcasecmp (term_program, "contour"))`

Yes, it was my failed first attempt. :)

**Comment by hpjansson** [comment]
I think your first try was correct, but it was checking the wrong env var. I'm not familiar with the Contour code, but at a glance, it seems to be setting TERMINAL_NAME, not TERM_PROGRAM. So if you compare against that env var, you should be fine.

Cf. https://github.com/contour-terminal/contour/blob/c786e4cc1d3c27f6e6d7bf0f309414c05eb301c6/src/contour/Config.cpp#L1012

**Comment by data-man** [comment]
`ok.png` ok

`$ chafa ok.png` with this PR
chafa1

`$ chafa ok.png` with `if (!g_ascii_strcasecmp (term_program, "contour"))`
chafa2

**Comment by hpjansson** [comment]
Right, but the PR just enables sixels everywhere where TERM_PROGRAM != "contour", which is pretty much always. You want to check for TERMINAL_NAME == "contour".

**Comment by hpjansson** [comment]
Looks good now, thanks a lot!

**Comment by christianparpart** [comment]
Hey guys.

I have been redirected here through https://github.com/contour-terminal/contour/discussions/416 and many thanks for your great work, I highly appreciate that.

I wanted to drop a note that there is a more reliable way that could be used for detecting supporting terminals apart from using environment variables (which can be forged or even get lost, e.g. when ssh'ing into another machine).

What works over the network though is `XTVERSION`:

```
        CSI > Ps q Ps = 0 ⇒ Report xterm name and version (XTVERSION). The response is a DSR sequence identifying the version: DCS > | text ST
```

Contour and a few others (that do happen to have Sixel support implemented too) have that VT sequence implemented and report back reliably.

**Comment by hpjansson** [comment]
Thanks for the note and for your great work in the terminal space! I'm aware that many terminals allow this to be queried, and would like to implement it in a future interactive version of Chafa. The current version is meant to also work when output is redirected e.g. to a file, so it's limited to a best-guess.

As for ssh, I'm actually looking at implementing distro patches to allow through one or more env vars in addition to TERM, since it's become very common for terminals to identify with TERM=xterm-256color + some other var. That's still not perfect, of course, since you could be starting a terminal from within another terminal (e.g. screen session) where the inner session inherits the (now improper) env.

**Pull request merged**
