### PR TITLE
Add python scripts for generating the chafa8x8 font.

### PR DESCRIPTION
**Pull request by cdluminate**
relicensed code under LGPLv3+. I need some time to find the best set of prebuilt font and fix font problems in different terminals. However anyone should be able to generate their custom font with these scripts.

On Debian fontforge doesn't support python3 so svg2ttf.py is for python2.

### CODE REVIEW

**Comment by cdluminate** [comment]
>  I can add a Makefile.am to dist the Python code. 

These scripts are still experimental. Don't use/install them by default in this stage.

**Comment by cdluminate** [comment]
> Likewise the C changes can wait until we're sure about how the custom font will fit in, and I think 65536 slots in the static array is a bit much, so I'll have to change the code to use alloca().

IIRC there is no much improvement between the 8192 and 65536 version. I'm still trying to reduce the number of glyphs while keeping the result as fancy as possible.

> Would it be possible to generate one with only 256 or 512 symbols?

I think at least 1024 or 2048 ... You can try generating your own font from you picture collection and see if 256/512 version looks fine ...

> That's still a lot more than we get with the Unicode block range.

We have enough space in the Unicode Private Use Area https://en.wikipedia.org/wiki/Private_Use_Areas

In my scripts the font code offset starts from plane 16.

**Comment by cdluminate** [comment]
```
215             f.write(template.format(w=62.5, h=127.5, x=0+c*62.5, y=-40+r*127.5))
```
I have to change this line to adapt to different terminals and fonts. Or there will be gap between those custom blocks.

**Comment by cdluminate** [comment]
One demo picture. This is produced under `sakura` terminal emulator, with `Inconsolata Medium, size=17` font.
image

**Comment by hpjansson** [comment]
There, moved it to tools/fontgen/ and added to dist so it will go in tarballs. It won't be installed, at least not yet.

**Pull request merged**
